import React from 'react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { downloadBlob } from './export.util';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 18,
    marginBottom: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#1f2937',
  },
  table: {
    width: '100%',
  },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    paddingVertical: 8,
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 6,
  },
  headerCell: {
    flex: 1,
    paddingHorizontal: 6,
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
    color: '#374151',
  },
  cell: {
    flex: 1,
    paddingHorizontal: 6,
    fontSize: 9,
    color: '#4b5563',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
  },
});

function PDFDocument({ data, columns, title }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <View style={styles.table}>
          <View style={styles.headerRow}>
            {columns.map((col, i) => (
              <Text key={i} style={styles.headerCell}>
                {col.label || col.key}
              </Text>
            ))}
          </View>
          {data.map((row, ri) => (
            <View key={ri} style={styles.row}>
              {columns.map((col, ci) => {
                let value = row[col.key];
                if (col.exportRender) value = col.exportRender(value, row);
                return (
                  <Text key={ci} style={styles.cell}>
                    {value != null ? String(value) : '-'}
                  </Text>
                );
              })}
            </View>
          ))}
        </View>
        <Text style={styles.footer}>
          Generated by PDFGenius - {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function exportToPDF(data, columns, title = 'Export', filename = 'export.pdf') {
  if (!data || data.length === 0) return;

  const doc = <PDFDocument data={data} columns={columns} title={title} />;
  const blob = await pdf(doc).toBlob();
  downloadBlob(blob, filename);
}
